### ISSUE TITLE
Handle 'key: NEWLINE value'

### ISSUE THREAD

**Issue by mikemaccana** [mikemaccana/whois-json#11]
See final unit test added to v2.0

**Comment by zbone3** [comment]
@mikemaccana 
I found the reason : 

You removed this line in page
`rawData = rawData.replace(/:\s*\r\n/g, ': ');`

right before
`var lines = rawData.split('\n');`

It's crucial for the correct split of the .co.uk whois results that look like: `key: \r\n value \r\n\r\n`

**Comment by mikemaccana** [comment]
I originally left it in, but it didn't work so I removed it. Could you send
a PR with the unit test fixed? That'll show the fix actually works for
geektools and .co.uk domains.  Thanks!

**Comment by zbone3** [comment]
Sure
See #12

**Comment by mikemaccana** [comment]
Wow it passes without changes?

**Comment by zbone3** [comment]
all 3 pass on my end..
I think the issue might have been that you used geektools.com:43 instead of just geektools.com

**Comment by zbone3** [comment]
Merged and working
Closed

**Comment by mikemaccana** [comment]
Hrm weird, `geektool.com:43` works (and matches the `whois` docs. A mystery! But yeah it works. Mild annoyance is `Results` becomes a field, so 

  {
    "results": "Domain name:         google.co.uk",
    "registrant": "Google Inc.",
    "registrantType": "Non-UK Corporation",
    "registrantSAddress": "1600 Amphitheatre Parkway",
    ...
  }

Which could be worth fixing if either you or me has time, but thanks!
