### ISSUE TITLE
Duplicate object keys not displaying properly

### ISSUE THREAD

**Issue by d30jeff** [mikemaccana/whois-json#3]
Repetitive object keys are replaced with the last one.

Example, the output returns 3 similar key, the output will be the last key.

```    
descr:          a
descr:          b
descr:          c
```

`//ouput: desr: c`

Thanks

**Comment by mikemaccana** [comment]
Want to send a PR?

**Comment by d30jeff** [comment]
Hello @mikemaccana, I have sent a pull request [here](https://github.com/mikemaccana/whois-json/pull/4).

**Comment by mikemaccana** [comment]
Published in 1.2 (also tests added). Note the PR made every key an array, so I rewrote it.
