### ISSUE TITLE
node-whois has been renamed to whois

### ISSUE THREAD

**Issue by Niffy** [mikemaccana/whois-json#7]
Got the following messages in an npm install.

npm WARN deprecated node-whois@2.1.3: WARNING: This project has been renamed from node-whois to whois. Install using whois instead.
npm WARN deprecated node-whois@2.1.0: WARNING: This project has been renamed from node-whois to whois. Install using whois instead.

Would be cool for this project to use the latest.

**Comment by mikemaccana** [comment]
Fixed!
