### ISSUE TITLE
Checks for options as function rather than object

### ISSUE THREAD

**Issue by spieglio** [mikemaccana/whois-json#8]
I kind of get the point of this to check for a function "as well" but in the doc, it mentions that you can also give an object which does not work because this line is not returning true for objects:

https://github.com/mikemaccana/whois-json/blob/1b40d454134cd44b3967c18e40a19c0f865392a9/index.js#L7

Should be relatively easy to fix? Or am I missing something?

**Comment by mikemaccana** [comment]
Function signature has changed in 2.0 (no callbacks), so closing
