### ISSUE TITLE
change-case in package.json incorrect

### ISSUE THREAD

**Issue by barakplasma** [mikemaccana/whois-json#9]
In https://github.com/mikemaccana/whois-json/blob/master/package.json#L16 you refer to change-case the wrong way.

I recommend re-installing it https://github.com/blakeembrey/change-case/blob/master/README.md#installation

**Comment by mikemaccana** [comment]
What does 'the wrong way' mean?

**Comment by barakplasma** [comment]
You resolved this 23 days ago in https://github.com/mikemaccana/whois-json/commit/b5610ee624aee21e3f723b73f14518e1cf65fdf5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L16
